source "https://rubygems.org"

gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'sqlite3'
gem 'pry'
gem 'require_all'
gem 'rack'
gem 'shotgun'
gem 'sinatra'
gem 'rest-client'


group :test do
  gem 'rspec', '3.3.0'
  gem 'capybara', '2.5.0'
  gem 'rack-test', '>= 0.5.4'
end
